# Generated by Django 3.0.1 on 2023-03-31 13:00

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image', models.ImageField(default='feras.png', upload_to='images')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='articale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=14)),
                ('content', models.TextField(max_length=200)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articales', to='feras.Auther')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
